config/routes.rb
Analytics1::Application.routes.draw do

  resources :rprocs

  resources :vtrs

  resources :reports

  resources :logs

  resources :periods

  get "welcome/index"

  resources :uploads, :periods, :reports, :analysis, :uplogs

  root :to => 'welcome#index'

  

end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :period, :report

  validates_presence_of :report
  validates_presence_of :period

  # global for dealing with reports
  Pnames = [] # will be filled-in at render time
  R2string = [1,'EAC Survey']
  String2r = [
               ['EAC Survey', 1]
             ]
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
    @report = Report.new
    @periods = Period.all # bfh: to support matching periods with reports
    @rprocs = Rproc.all # bfh: to support matching reports with report procedures

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reports }
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @report = Report.find(params[:id])
    @rprocs = Rproc.all # bfh: to support matching reports with report procedures
    @periods = Period.all # bfh: to support matching periods with reports

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/new
  # GET /reports/new.json
  def new
    @report = Report.new
    @periods = Period.all # bfh: to support matching periods with reports

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/1/edit
  def edit
    @periods = Period.all # bfh: to support matching periods with reports
    @rprocs = Rproc.all # bfh: to support matching reports with report procedures
    @report = Report.find(params[:id])
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(params[:report])
    @periods = Period.all # bfh: to support matching periods with reports

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render json: @report, status: :created, location: @report }
      else
        format.html { render action: "new" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.json
  def update
    @report = Report.find(params[:id])

    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper

  # GenRept is a simple dispatch routine, calling report generation based on ID
  def GenRept(report)
    # parameter is a report job description
    rproc_id = report.report
    period_name = report.period

    # expand period name into parameters
    period = Hash.new()
    @periods.each do |tmp|
      if tmp.name == period_name
	period['ptype'] = tmp.ptype
	period['lodate'] = tmp.lodate
	period['hidate'] = tmp.hidate
	period['voter_reg_lodate'] = tmp.voter_reg_lodate
	period['voter_req_hidate'] = tmp.voter_reg_hidate
	break
      end
    end

    retval = ''

    # case maps rproc IDs to code to implement that reprot
    case rproc_id
    when 1
      retval = DoR1(period)
    when 2
      retval = DoR2(period)
    else
      retval = 'Rproc #{rproc_id} is not supported'   	
    end

    retval
  end

  #
  # these functions implement the reports
  #

  def DoR1(period)
    retval = '' # what we return
    accum = Hash.new() # where we accumulate data to report

    # get a list of VTRs between these dates and make a hash of the formNote
    rows = Vtr.where("date(date) between ? and ?", period['lodate'].to_s(:db), period['hidate'].to_s(:db))
    rows.each do |row|
      k = row['formNote']
      accum[k] = 0 if accum[k].nil?
      accum[k] += 1
    end

    retval = accum.inspect
  end

  def DoR2(period)
    retval = '' # what we return
    accum = Hash.new() # where we accumulate data to report

    # get a list of VTRs between these dates and count transactions by voter id
    rows = Vtr.where("date(date) between ? and ?", period['lodate'].to_s(:db), period['hidate'].to_s(:db))
    rows.each do |row|
      k = row['voterid']
      accum[k] = 0 if accum[k].nil?
      accum[k] += 1
    end

    # scan accumulator, get the min, max and average
    tot = count = 0
    min = max = nil
    accum.each do |k,v|
      # handle initialization
      min = v if min.nil?
      max = v if max.nil?

      tot += v
      count += 1

      min = v if (v < min)
      max = v if (v > max)
    end
    avg = tot / count if count > 0

    retval = "Tranactions per voter: min=#{min} max=#{max} average=#{avg}"
  end

end

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :report %><br />
<!--    <%= f.text_field :report %> -->
    <%=
	# get the list of report procedures, sort by name, make an HTML select
	rproclist = Hash.new()
	@rprocs.each do |rproc|
	  rproclist[rproc['name']] = rproc['id']
	end

	# make the HTML select
        f.select(
	  :report, 
	  options_for_select(
	    rproclist,
	    :report.to_s
	  )
	)
     %>
  </div>
  <div class="field">
    <%= f.label :period %><br />
<!--    <%= f.text_field :period %> -->
    <%=
	# get a hash of period names
	Report::Pnames.clear
	@periods.each do |p|
	    Report::Pnames << p.name
	end

	if params[:period].nil?
	  default_period = nil
	  sel_opt = {}
	else
	  default_period = params[:period]
	  sel_opt = {:disabled => true}
	end

	# create a select out of those period names
        f.select(
	  :period, 
	  options_for_select(
	    Report::Pnames,
	    default_period
	  ),
	  {},
	  sel_opt
	)

     %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
      <h2><%=t('landing_page.reports')%></h2>
      <p><%=t('reports_page.text')%></p>

      <p>
<%
  status = flash[:status]
  if !status.nil?
    if status.include? "[0]"
        color = t('upload_page.ok_color')
        msg = 'OK'
    else
        color = t('upload_page.fail_color')
        msg = 'FAIL'
    end
  end

  # get the list of report procedures, sort by name, make an HTML select
  rproclist = Hash.new()
  @rprocs.each do |rproc|
    rproclist[rproc['id']] = rproc['name']
  end
%>
  <span style="background-color: <%= color %>;"> <%= msg %> </span>
<%= flash[:status] %>
      </p>

<%= render 'form' %>

      <p>&nbsp;</p>
      <h3><%=t('reports_page.history_header')%></h3>

<table border=0 cellspacing="3" cellpadding="3" style="border-width:1px;border-color:black;border-style:solid;">
  <tr>
    <th>Report</th>
    <th>Period</th>
    <th>Created</th>
    <th>Last Run</th>
    <th></th>
<!--
    <th></th>
    <th></th>
-->
    <th></th>
    <th></th>
  </tr>

<% @reports.each do |report| %>
  <tr>
<!--    <td><%= report.report %></td> -->
    <td>
      <%= rproclist[report.report] %>
    </td>
    <td><%= report.period %></td>
    <td><%= report.created_at %></td>
    <td><%= report.updated_at %></td>
    <td><%= link_to t('reports_page.make_button_text'), report %></td>
<!--
    <td><%= link_to 'View', '' %></td>
    <td><%= link_to 'Show', report %></td>
-->
    <td><%= link_to 'Edit', edit_report_path(report) %></td>
    <td><%= link_to 'Remove', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/reports/new.html.erb
<h1>New report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<%
  # get the list of report procedures, sort by name, make an HTML select
  rproclist = Hash.new()
  @rprocs.each do |rproc|
    rproclist[rproc['id']] = rproc['name']
  end
 %>

<p>
  <b>Report:</b>
<!--  <%= @report.report %> -->
  <%=
    rproclist[@report.report]
  %>
</p>

<p>
  <b>Period:</b>
  <%= @report.period %>
</p>

<p>
  <b>Output:</b>
</p>
<%= GenRept(@report) %>

<p><cite>Report Ends</cite></p>
<!-- <%= link_to 'Edit', edit_report_path(@report) %> | -->
<%= link_to 'Back', reports_path %>